FROM golang:1.17.0 AS stage

WORKDIR /src/

COPY . .

RUN go build -o /app/webapi .cmd/webapi

FROM debian:bullseye

EXPOSE 3000

VOLUME /data

WORKDIR /app/

COPY --from=builder /app/weapi ./

CMD ["/app/webapi"]
